### ISSUE TITLE
Your results / MSE metric in your code

### ISSUE THREAD

**Issue by agethen** [rohanchandra30/Spectral-Trajectory-Prediction#2]
Hi,
I was reading your paper with interest. However, when looking at your code, I found something rather odd. In your evaluation code [(here)](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/master/ours/def_train_eval.py#L472), it seems that you are "normalizing" the GT trajectories. 

Could it be that I misunderstood something? Obviously you cannot normalize those. It is especially bad since your baselines (e.g., [Encoder-Decoder](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/master/comparison_method/EncDec/def_train_eval.py#L212)) are not "normalizing" the groundtruth data -- so not only are the results meaningless, they cannot even be compared.

Apart from that, in the paper abstract it appears as if you are using Graph Convolution Networks, but from the code [(here)](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/master/ours/models.py#L110) it seems they are permanently disabled. Do the results in the paper use GCNs?

Looking forward to your reply!
 Sebastian

**Comment by rohanchandra30** [comment]
Hi,

We scale the GT since the output of the LSTM are mean and covariance, and the scale of that (<1) differs significantly from the scale of GT which in the case of LYFT crosses above 1000. So we scaled GT.

We scale for Encode-Decoder [here](https://github.com/rohanchandra30/Spectral-Trajectory-Prediction/blob/b85b4f8014aa479d4560b90936b18fd2361af90d/comparison_method/EncDec/def_train_eval.py#L183). 

The mention of GCN is actually a typo. We are aware of that and plan to fix that later. None of the results use GCN

**Comment by agethen** [comment]
Thanks for the explanation! Seeing the two different MSE implementations got me worried, since the improvement is quite a lot.

So, the trajectory labels are all normalized in the same manner for each method (including CS-LSTM and Social-GAN, which are not in the repo here) in Table 2, and therefore comparable. 

I think a more natural way might be to first predict normalized coordinates as you do, but then re-transform everything back into the original coordinate space for the MSE computation :)
Thanks!

**Comment by rohanchandra30** [comment]
haha agreed ! And in fact, that is what we tried first, since as you said, it is more natural to scale the predictions *up* to GT, rather than scaling the GT *down* to the predictions !

Unfortunately, in the first case, for some of the other comparison methods, we kept running into inexplicable crashes after every few epochs. We are currently working to diagnose those crashes. Once we have a solution, we will update the code. 

For those few epochs where the first scaling method did work, we noted that the MSE in either scaling direction yielded similar numbers, so our results are not biased :) In the interest of complete transparency, we will post the MSE numbers for both scaling methods to show that our scaling is not biased, rather is equivalent to scaling in either direction.

Thanks for your question. Good insights !
